#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
CODEX_DIR="$REPO_DIR/.codex"
REFS_DST="$CODEX_DIR/references"
COMMANDS_DST="$CODEX_DIR/commands"
SKILL_DST="$CODEX_DIR/skill"

# ---------------------------------------------------------------------------
# Portable inode helper (macOS uses -f, Linux uses -c)
# ---------------------------------------------------------------------------

get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Build AGENTS.md
#
# Flattens all 3 rules files from content/rules/ into a single AGENTS.md,
# which Codex loads automatically from the project root. A header and
# protocol reference footer are prepended/appended.
# ---------------------------------------------------------------------------

AGENTS_DST="$CODEX_DIR/AGENTS.md"

{
  cat <<'HEADER'
# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every Codex session in this repository.

**Note:** This file is auto-generated by `.codex/build.sh` from `content/rules/`. Do not edit it directly - edit the source files in `content/rules/` instead.

For detailed protocol specs (Skeptic loop, subagent protocol, agent team), see the reference docs in `~/.agents/skills/agentic-engineering/references/` (installed globally) or `.codex/references/` (local copies).

---

HEADER

  cat "$CONTENT/rules/agent-methodology.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals

These live in `~/.agents/skills/agentic-engineering/references/` (global install) or `.codex/references/` (local copies).

For command templates (skeptic, implement, wrap, etc.), see `.codex/commands/`.
FOOTER

} > "$AGENTS_DST"

echo "Built AGENTS.md"

# ---------------------------------------------------------------------------
# Build skill directory
#
# The Codex skill lives at .codex/skill/ (staging) and gets symlinked to
# ~/.agents/skills/agentic-engineering/ by install.sh. It contains:
#   - SKILL.md          (trigger metadata + methodology summary)
#   - references/       (hardlinks to content/references/)
# ---------------------------------------------------------------------------

mkdir -p "$SKILL_DST/references"

# References: hardlink from content/ so edits stay in sync
hardlink_from_content() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]] && [[ "$(get_inode "$src")" == "$(get_inode "$dst")" ]]; then
    return
  fi
  rm -f "$dst"
  ln "$src" "$dst"
}

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$SKILL_DST/references/$(basename "$src")"
done

echo "Rebuilt skill/references/ hardlinks"

# SKILL.md is a static file maintained in .codex/skill/SKILL.md
# (not generated - its frontmatter and body are hand-authored for Codex's skill format)
if [[ ! -f "$SKILL_DST/SKILL.md" ]]; then
  echo "WARNING: $SKILL_DST/SKILL.md is missing - run install.sh to initialize it"
fi

# ---------------------------------------------------------------------------
# Build .codex/references/ (local project copies)
#
# .codex/references/ contains hardlinks to content/references/ for users
# browsing the repo without installing. .codex/skill/references/ is a
# symlink to .codex/references/ so there is one source of truth.
# ---------------------------------------------------------------------------

mkdir -p "$REFS_DST"

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$REFS_DST/$(basename "$src")"
done

# Make skill/references/ a symlink to .codex/references/ (single source of truth)
if [[ -L "$SKILL_DST/references" ]]; then
  current_target="$(readlink "$SKILL_DST/references")"
  if [[ "$current_target" != "$REFS_DST" ]]; then
    rm "$SKILL_DST/references"
    ln -s "$REFS_DST" "$SKILL_DST/references"
  fi
elif [[ -d "$SKILL_DST/references" ]]; then
  # Was a real directory (old hardlink set) - replace with symlink
  rm -rf "$SKILL_DST/references"
  ln -s "$REFS_DST" "$SKILL_DST/references"
else
  ln -s "$REFS_DST" "$SKILL_DST/references"
fi

echo "Rebuilt references/ hardlinks"

# ---------------------------------------------------------------------------
# Build .codex/commands/ (hardlinks from content/commands/, no transforms)
#
# Commands are hardlinked from content/commands/ as-is. The
# /agentic-engineering prerequisite blockquote is NOT present in content/
# (it is Claude Code-specific and prepended only by .claude/build.sh),
# so no transform is needed here.
# ---------------------------------------------------------------------------

mkdir -p "$COMMANDS_DST"

for src in "$CONTENT/commands/"*.md; do
  name="$(basename "$src")"
  hardlink_from_content "$src" "$COMMANDS_DST/$name"
done

echo "Rebuilt commands/ hardlinks"

echo "Codex adapter build complete."
