#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
CODEX_DIR="$REPO_DIR/.codex"
REFS_DST="$CODEX_DIR/references"
COMMANDS_DST="$CODEX_DIR/commands"
SKILL_DST="$CODEX_DIR/skill"

# ---------------------------------------------------------------------------
# Portable inode helper (macOS uses -f, Linux uses -c)
# ---------------------------------------------------------------------------

get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Build AGENTS.md
#
# Assembles the methodology body via scripts/build-methodology.sh (which
# reads content/sections/) then appends the remaining rules files, all into
# a single AGENTS.md that Codex loads automatically from the project root.
# A header and protocol reference footer are prepended/appended.
# ---------------------------------------------------------------------------

AGENTS_DST="$CODEX_DIR/AGENTS.md"

{
  cat <<'HEADER'
# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every Codex session in this repository.

**Note:** This file is auto-generated by `.codex/build.sh`. Do not edit it directly - edit the source files in `content/sections/` (methodology) or `content/rules/` (other rules) instead.

For detailed protocol specs (Skeptic loop, subagent protocol, agent team), see the reference docs in `~/.agents/skills/agentic-engineering/references/` (installed globally) or `.codex/references/` (local copies).

---

HEADER

  bash "$REPO_DIR/scripts/build-methodology.sh"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals

These live in `~/.agents/skills/agentic-engineering/references/` (global install) or `.codex/references/` (local copies).

For command templates (skeptic, implement-ticket, wrap, etc.), see `.codex/commands/`.
FOOTER

} > "$AGENTS_DST"

echo "Built AGENTS.md"

# ---------------------------------------------------------------------------
# Build skill directory
#
# The Codex skill lives at .codex/skill/ (staging) and gets symlinked to
# ~/.agents/skills/agentic-engineering/ by install.sh. It contains:
#   - SKILL.md          (trigger metadata + methodology summary)
#   - references/       (hardlinks to content/references/)
# ---------------------------------------------------------------------------

mkdir -p "$SKILL_DST/references"

# References: hardlink from content/ so edits stay in sync
hardlink_from_content() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]] && [[ "$(get_inode "$src")" == "$(get_inode "$dst")" ]]; then
    return
  fi
  rm -f "$dst"
  ln "$src" "$dst"
}

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$SKILL_DST/references/$(basename "$src")"
done

echo "Rebuilt skill/references/ hardlinks"

# SKILL.md is a static file maintained in .codex/skill/SKILL.md
# (not generated - its frontmatter and body are hand-authored for Codex's skill format)
if [[ ! -f "$SKILL_DST/SKILL.md" ]]; then
  echo "WARNING: $SKILL_DST/SKILL.md is missing - run install.sh to initialize it"
fi

# ---------------------------------------------------------------------------
# Build .codex/references/ (local project copies)
#
# .codex/references/ contains hardlinks to content/references/ for users
# browsing the repo without installing. .codex/skill/references/ is a
# symlink to .codex/references/ so there is one source of truth.
# ---------------------------------------------------------------------------

mkdir -p "$REFS_DST"

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$REFS_DST/$(basename "$src")"
done

# Make skill/references/ a symlink to ../references (single source of truth)
# Use a RELATIVE target so the symlink stays valid regardless of repo location.
if [[ -L "$SKILL_DST/references" ]]; then
  current_target="$(readlink "$SKILL_DST/references")"
  if [[ "$current_target" != "../references" ]]; then
    rm "$SKILL_DST/references"
    ln -s "../references" "$SKILL_DST/references"
  fi
elif [[ -d "$SKILL_DST/references" ]]; then
  # Was a real directory (old hardlink set) - replace with symlink
  rm -rf "$SKILL_DST/references"
  ln -s "../references" "$SKILL_DST/references"
else
  ln -s "../references" "$SKILL_DST/references"
fi

echo "Rebuilt references/ hardlinks"

# project-scaffolding.yml and templates/: hardlink into .codex/skill/ so agentic-migrate can find them
hardlink_from_content "$CONTENT/project-scaffolding.yml" "$SKILL_DST/project-scaffolding.yml"
mkdir -p "$SKILL_DST/templates/.agentic"
for tmpl_name in config.json learnings.md; do
  hardlink_from_content "$CONTENT/templates/.agentic/$tmpl_name" "$SKILL_DST/templates/.agentic/$tmpl_name"
done
echo "Rebuilt skill/project-scaffolding.yml and templates/"

# ---------------------------------------------------------------------------
# Build .codex/commands/ (hardlinks from content/commands/, no transforms)
#
# Commands are hardlinked from content/commands/ as-is. The
# /agentic-engineering prerequisite blockquote is NOT present in content/
# (it is Claude Code-specific and prepended only by .claude/build.sh),
# so no transform is needed here.
# ---------------------------------------------------------------------------

mkdir -p "$COMMANDS_DST"

for src in "$CONTENT/commands/"*.md; do
  name="$(basename "$src")"
  hardlink_from_content "$src" "$COMMANDS_DST/$name"
done

echo "Rebuilt commands/ hardlinks"

# ---------------------------------------------------------------------------
# Build .codex/agents/ (generated TOML files from content/agents/*.md)
#
# Each content/agents/<name>.md has YAML frontmatter (name, description,
# model, tools) followed by the agent body. The body becomes
# developer_instructions in the TOML file. Only name and description are
# written to the TOML - the model field is intentionally omitted so agents
# inherit the session model. The Claude-specific model and tools: fields
# have no useful Codex TOML equivalent and are silently dropped.
#
# The /agentic-engineering prerequisite blockquote (Claude Code-specific) is
# stripped from the body before writing to developer_instructions. Any line
# matching "> **Prerequisite:**.*agentic-engineering" and any immediately
# following blockquote continuation lines ("> ...") are removed, along with
# one trailing blank line if present.
#
# This keeps content/agents/*.md as the single source of truth - editing
# there regenerates the TOML on the next build.
# ---------------------------------------------------------------------------

AGENTS_TOML_DST="$CODEX_DIR/agents"
mkdir -p "$AGENTS_TOML_DST"

# Track which TOML files we generated so we can remove stale ones below.
declare -a generated_tomls=()

for src in "$CONTENT/agents/"*.md; do
  [ -f "$src" ] || continue

  # --- Parse frontmatter ---
  # Extract the YAML block between the first pair of --- delimiters.
  fm_name=""
  fm_description=""
  fm_model=""
  in_fm=0
  past_fm=0
  body_lines=()

  while IFS= read -r line; do
    if [[ $in_fm -eq 0 && $past_fm -eq 0 ]]; then
      if [[ "$line" == "---" ]]; then
        in_fm=1
        continue
      fi
    fi
    if [[ $in_fm -eq 1 ]]; then
      if [[ "$line" == "---" ]]; then
        in_fm=0
        past_fm=1
        continue
      fi
      # Parse simple key: value pairs (no nested YAML)
      key="${line%%:*}"
      val="${line#*: }"
      # Strip leading/trailing whitespace from val
      val="${val#"${val%%[![:space:]]*}"}"
      val="${val%"${val##*[![:space:]]}"}"
      case "$key" in
        name)        fm_name="$val" ;;
        description) fm_description="$val" ;;
        model)       fm_model="$val" ;;
      esac
      continue
    fi
    # Past frontmatter: accumulate body lines
    if [[ $past_fm -eq 1 ]]; then
      body_lines+=("$line")
    fi
  done < "$src"

  if [[ -z "$fm_name" ]]; then
    echo "WARNING: $src has no 'name' in frontmatter - skipping"
    continue
  fi
  if [[ -z "$fm_description" ]]; then
    echo "WARNING: $src has no 'description' in frontmatter - skipping"
    continue
  fi

  # model is intentionally not written to TOML - agents inherit the session
  # model. Anthropic model IDs (claude-*) are not valid in Codex anyway.

  # Strip /agentic-engineering prerequisite blockquotes from body.
  # Pattern: a line starting with "> " that contains "/agentic-engineering"
  # followed by any immediately-following blockquote continuation lines
  # (lines that start with ">"), followed by one optional blank line.
  # Use a simple state-machine line-skip rather than fragile regex.
  filtered_body_lines=()
  skip_next_blockquotes=0
  skip_one_blank=0
  for bline in "${body_lines[@]}"; do
    if [[ $skip_next_blockquotes -eq 1 ]]; then
      # Still inside the blockquote block - skip continuation lines
      if [[ "$bline" == ">"* ]]; then
        continue
      fi
      skip_next_blockquotes=0
      skip_one_blank=1
    fi
    if [[ $skip_one_blank -eq 1 ]]; then
      skip_one_blank=0
      if [[ -z "$bline" ]]; then
        # Blank line immediately after stripped blockquote - skip it too
        continue
      fi
      # Not blank - keep it and fall through to normal processing
    fi
    # Detect the prerequisite blockquote line
    if [[ "$bline" == ">"* ]] && echo "$bline" | grep -q "/agentic-engineering"; then
      skip_next_blockquotes=1
      continue
    fi
    filtered_body_lines+=("$bline")
  done
  body_lines=("${filtered_body_lines[@]+"${filtered_body_lines[@]}"}")

  # Build the body string: join accumulated lines.
  # We need to escape backslash and double-quote for the TOML triple-quoted
  # string. In TOML """ strings, only backslash requires escaping; double
  # quotes are allowed as long as three consecutive ones are not present.
  # We escape backslash as \\ and replace any run of 3+ double-quotes with
  # escaped variants to be safe.
  body_content=""
  first_body=1
  for bline in "${body_lines[@]}"; do
    if [[ $first_body -eq 1 ]]; then
      body_content="$bline"
      first_body=0
    else
      body_content="$body_content
$bline"
    fi
  done

  # Escape backslashes for TOML multi-line basic string
  body_escaped="${body_content//\\/\\\\}"
  # Escape sequences of 3+ double-quotes so they don't terminate the TOML string
  body_escaped="${body_escaped//\"\"\"/\\\"\\\"\\\"}"

  # Escape description for a TOML basic string (escape backslash then double-quote)
  desc_escaped="${fm_description//\\/\\\\}"
  desc_escaped="${desc_escaped//\"/\\\"}"

  dst="$AGENTS_TOML_DST/${fm_name}.toml"
  generated_tomls+=("${fm_name}.toml")

  {
    echo "# Generated by .codex/build.sh from content/agents/$(basename "$src")"
    echo "# Do not edit directly - edit the source markdown file instead."
    echo ""
    echo "name        = \"${fm_name}\""
    echo "description = \"${desc_escaped}\""
    echo ""
    echo "developer_instructions = \"\"\""
    printf '%s' "$body_escaped"
    echo ""
    echo "\"\"\""
  } > "$dst"

done

# Remove stale TOML files (present in agents/ but not generated this run)
for existing in "$AGENTS_TOML_DST"/*.toml; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_tomls[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale agent TOML: $bname"
  fi
done

echo "Built ${#generated_tomls[@]} agent TOML files in .codex/agents/"

echo "Codex adapter build complete."
