#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

CONTENT_DIR="$REPO_DIR/content"
HERMES_DIR="$REPO_DIR/.hermes"

echo "Building Hermes adapter..."

# ---------------------------------------------------------------------------
# Assemble the main SKILL.md
# ---------------------------------------------------------------------------

cat > "$HERMES_DIR/SKILL.md" <<'HEADER'
---
name: agentic-engineering
description: >
  Agentic Engineering Protocol for Hermes - structured delegation model,
  risk classification, adversarial review loops, code quality gates,
  git workflow conventions, and named agent definitions. Load this skill
  when doing AI-assisted software development with Hermes Agent.
version: 1.0.0
author: Hermes Agent + Agentic Engineering Contributors
license: MIT
metadata:
  hermes:
    tags: [agentic-engineering, software-development, delegation, quality-assurance, git-workflow, coding-standards]
    related_skills: [claude-code, codex, github]
---

# Agentic Engineering Protocol (Hermes)

A portable methodology for AI-assisted software development. Provides structured delegation, risk classification, adversarial review, code quality gates, and git workflow conventions.

**Source of truth:** All content is generated from `content/` in the agentic-engineering repo. Do not edit this file directly - edit sources and run `.hermes/build.sh`.

**Live docs:** https://docs.dinostack.ai

**Repo:** `~/DinoStack/`

---

## Activation Preflight

Before applying this methodology in any project, run this check once per session. It governs whether the protocol is active for the current project.

1. **Read the global mode.** Load `~/.hermes/agentic-engineering.json`. If missing, assume `mode=opt-out`. Expected shape: `{ "mode": "opt-out" | "opt-in", "set_at": "<ISO8601>" }`.
2. **Read the project marker.** Look for a root `AGENTS.md` in the current working directory.
3. **Scan for the marker line.** Case-insensitive whole-line match (allow leading `- `):
   - `agentic-engineering: opt-in`
   - `agentic-engineering: opt-out`
   If both appear, the first one wins. Warn: `both opt-in and opt-out markers found - using the first one (<value>)`.
4. **Activation decision:**
   - `mode=opt-out` AND `marker=opt-out` → inactive
   - `mode=opt-in` AND `marker != opt-in` → inactive
   - All other combinations → **active**
5. **When inactive:** print one line and stop: `agentic-engineering: inactive in this project (mode=<mode>, marker=<marker>). Add 'agentic-engineering: opt-in' to AGENTS.md to activate.`

**Graceful defaults:** missing config, missing AGENTS.md, malformed JSON all resolve to "proceed active" (mode=opt-out, marker=none).

---

HEADER

# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

echo "  + embedding rules..."

cat >> "$HERMES_DIR/SKILL.md" <<'RULES_HEADER'
## Rules

RULES_HEADER

for f in "$CONTENT_DIR/rules/"*.md; do
  name=$(basename "$f")
  echo "### ${name%.md}" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  cat "$f" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  echo "---" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
done

# ---------------------------------------------------------------------------
# Reference Docs (embedded as sections)
# ---------------------------------------------------------------------------

echo "  + embedding reference docs..."

cat >> "$HERMES_DIR/SKILL.md" <<'REFS_HEADER'
## Reference Docs

REFS_HEADER

for f in "$CONTENT_DIR/references/"*.md; do
  name=$(basename "$f")
  echo "### ${name%.md}" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  cat "$f" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  echo "---" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
done

# ---------------------------------------------------------------------------
# Agent Definitions
# ---------------------------------------------------------------------------

echo "  + embedding agent definitions..."

cat >> "$HERMES_DIR/SKILL.md" <<'AGENTS_HEADER'
## Agent Team

Named specialist agents available for delegation. Spawn via `delegate_task` or use their definitions as prompts.

AGENTS_HEADER

for f in "$CONTENT_DIR/agents/"*.md; do
  name=$(basename "$f" .md)
  echo "### $name" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  cat "$f" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  echo "---" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
done

# ---------------------------------------------------------------------------
# Commands (as workflow patterns)
# ---------------------------------------------------------------------------

echo "  + embedding commands..."

cat >> "$HERMES_DIR/SKILL.md" <<'CMDS_HEADER'
## Commands / Workflow Patterns

These are the standard workflows. In Hermes, invoke them by creating a todo list and working through the steps, or by asking the agent to run the named workflow.

CMDS_HEADER

for f in "$CONTENT_DIR/commands/"*.md; do
  name=$(basename "$f" .md)
  echo "### /$name" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  # Strip the Claude-specific /agentic-engineering prerequisite blockquote if present
  sed '/^> \/agentic-engineering/d' "$f" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
  echo "---" >> "$HERMES_DIR/SKILL.md"
  echo "" >> "$HERMES_DIR/SKILL.md"
done

echo "Built: $HERMES_DIR/SKILL.md"
