#!/usr/bin/env bash
# Module: .copilot/build.sh
# Role: Build script for the VS Code Copilot adapter
# Inputs: content/rules/*.md, content/references/*.md, content/commands/*.md, content/agents/*.md,
#         scripts/build-methodology.sh
# Outputs: .github/copilot-instructions.md (auto-loaded by VS Code Copilot),
#          .github/agents/*.md (17 agent files for Copilot agent picker),
#          .github/prompts/*.prompt.md (22 slash-prompt files),
#          .github/instructions/content-engineering.instructions.md,
#          .github/hooks/* (hook scripts),
#          .copilot/references/*.md (hardlinks for repo browsing)
# Side-effects: removes stale generated files from previous builds;
#               absolute paths embedded in hook scripts at build time
# Consumers: .copilot/install.sh, hooks/pre-commit
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
GH="$REPO_DIR/.github"
COPILOT_DIR="$REPO_DIR/.copilot"
REFS_DST="$COPILOT_DIR/references"
AGENTS_DST="$GH/agents"
PROMPTS_DST="$GH/prompts"
INSTRUCTIONS_DST="$GH/instructions"
HOOKS_DST="$GH/hooks"

# ---------------------------------------------------------------------------
# Portable inode helper (macOS uses -f, Linux uses -c)
# ---------------------------------------------------------------------------

get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Step 1: Generate .github/copilot-instructions.md
#
# VS Code Copilot loads .github/copilot-instructions.md automatically in every
# chat session for the workspace. This file assembles the full methodology
# kernel + code-standards + conventions, then appends a footer listing the
# content/references/*.md filenames as read-on-trigger cues pointing at
# .copilot/references/ (reference bodies are NOT inlined).
# ---------------------------------------------------------------------------

mkdir -p "$GH"
INSTRUCTIONS_MD="$GH/copilot-instructions.md"

{
  cat <<'HEADER'
<!-- Auto-generated by .copilot/build.sh from content/rules/ — do not edit directly. -->
<!-- Edit source files in content/rules/ then re-run bash .copilot/build.sh -->

# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every VS Code Copilot
session for this workspace.

For detailed protocol specs, see reference docs in `.copilot/references/` (local
copies hardlinked from `content/references/`). Use the `.github/agents/` picker
to spawn named agents. Use `.github/prompts/` for slash-prompt commands.

---

HEADER

  bash "$REPO_DIR/scripts/build-methodology.sh"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs in `.copilot/references/` (or
`~/.copilot/references/` after install). Read these files on the triggers described
in the methodology above:

- `activation-detail.md` - activation preflight steps 5-6 detail
- `agent-team.md` - named agent roles, composed flows, decision rules
- `capability-preflight.md` - tool availability checks before agent spawns
- `capture-classification.md` - MUST/SHOULD/SKIP table for learnings captures
- `code-standards-detail.md` - per-language strict defaults, browser verification
- `conductor-operating-rules.md` - permission-blocked fallback, wrap-ticket carve-out
- `conventions-detail.md` - intent layer, context economy, external comment rules
- `cross-harness-teams.md` - dispatching Workers to other CLI harnesses
- `cross-session-loop-resume.md` - cross-session loop resume disk-write discipline
- `delegation-detail.md` - worker autonomy contract, stop-frequency, investigator rules
- `design-goals.md` - system design principles and goals
- `digest-return-pattern.md` - digest return discipline for background spawns
- `doc-sync-obligation.md` - trigger predicate and doc update obligations
- `events-log.md` - V1 telemetry event schemas, append discipline
- `frontend-discipline.md` - semantic HTML, ARIA, keyboard, focus, motion, tokens
- `model-discovery.md` - model routing and discovery rules
- `multi-developer-coordination.md` - multi-developer session coordination
- `planning-artifacts.md` - Brief and Plan templates, promotion mechanics
- `qa-gate.md` - parallel QA gate flow, dev-server boot pattern
- `qa-regression-obligation.md` - QA fix engineer regression-test obligation
- `regression-test-obligation.md` - Skeptic fix regression-test obligation
- `risk-config-and-tiers.md` - config toggle catalog, graph-derived risk, tier detail
- `role-models.md` - role-to-model mapping rules
- `skeptic-protocol.md` - Skeptic loop, findings classification, sign-off format
- `spawn-presets.md` - per-spawn capability bundle protocol
- `subagent-protocol.md` - parallel spawning rules, worktree isolation, phase breadcrumbs
- `task-state-file.md` - multi-unit task state schema and protocol
- `trigger-catalog.md` - manual/scheduled/action-triggered workflow types
- `worktree-lifecycle.md` - isolation and feature worktree cleanup commands
- `wrap-context-format.md` - context.md format for /wrap and stop hook

For slash-prompt commands (implement-ticket, skeptic, wrap, etc.), see `.github/prompts/`.
For named agent definitions, see `.github/agents/`.
FOOTER

} > "$INSTRUCTIONS_MD"

echo "Built .github/copilot-instructions.md"

# ---------------------------------------------------------------------------
# Step 2: Hardlink references/
#
# .copilot/references/ contains hardlinks to content/references/ for users
# browsing the repo without installing.
# ---------------------------------------------------------------------------

mkdir -p "$REFS_DST"

hardlink_from_content() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]] && [[ "$(get_inode "$src")" == "$(get_inode "$dst")" ]]; then
    return
  fi
  rm -f "$dst"
  ln "$src" "$dst"
}

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$REFS_DST/$(basename "$src")"
done

echo "Rebuilt .copilot/references/ hardlinks"

# ---------------------------------------------------------------------------
# Step 3: Generate .github/agents/*.md (one per content/agents/*.md)
#
# VS Code Copilot agent files use YAML frontmatter with these fields:
#   name:        (string, verbatim from source)
#   description: (double-quoted string)
#   tools:       (YAML flow array using Copilot tool names)
#
# Tool name mapping (Claude Code -> Copilot):
#   Read  -> read       Glob  -> search     Grep  -> search
#   Bash  -> execute    Write -> edit       Edit  -> edit
#   Task  -> agent
#
# Tool-grant rule:
#   - No Write/Edit/Task in source (read-only role) -> [read, search, execute]
#   - Has Write or Edit -> include edit
#   - Has Task          -> include agent
#
# model: is STRIPPED entirely (never emitted).
# agents: is NOT emitted (no such Copilot key).
# Body: strip_prereq() applied via inline Python.
# ---------------------------------------------------------------------------

mkdir -p "$AGENTS_DST"

declare -a generated_agents=()

for src in "$CONTENT/agents/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src")"
  dst="$AGENTS_DST/$base"
  generated_agents+=("$base")

  python3 - "$src" "$dst" "$REPO_DIR" <<'PYEOF'
import sys, re, os

src_path, dst_path, repo_dir = sys.argv[1], sys.argv[2], sys.argv[3]
sys.path.insert(0, repo_dir + '/scripts/lib')
from prereq_strip import strip_prereq

with open(src_path) as f:
    raw = f.read()

# Parse frontmatter
fm_match = re.match(r'^---\n(.*?)\n---\n(.*)', raw, re.DOTALL)
if not fm_match:
    sys.exit("No frontmatter found in " + src_path)

fm_text = fm_match.group(1)
body = fm_match.group(2)

# Extract name
name_match = re.search(r'^name:\s*(.*)', fm_text, re.MULTILINE)
name = name_match.group(1).strip() if name_match else os.path.basename(src_path).replace('.md', '')

# Extract description (handle multiline > block scalar and single-line)
desc_match = re.search(r'description:\s*>([\s\S]*?)(?=\n\w|\n---|\Z)', fm_text)
if not desc_match:
    desc_match = re.search(r'description:\s*(.*)', fm_text)
desc = desc_match.group(1).strip().replace('\n', ' ') if desc_match else name
# Collapse multiple spaces
desc = re.sub(r'  +', ' ', desc)

# Extract tools
tools_match = re.search(r'^tools:\s*(.*)', fm_text, re.MULTILINE)
tools_str = tools_match.group(1).strip() if tools_match else ''

# disallowedTools check - strip brackets/quotes and build a set
disallowed_match = re.search(r'^disallowedTools:\s*\[(.*?)\]', fm_text, re.MULTILINE)
disallowed_set = set()
if disallowed_match:
    for t in disallowed_match.group(1).split(','):
        disallowed_set.add(t.strip().strip('"\''))

# Determine which Claude Code tools are actually granted
# tools_str may be comma-separated or a YAML flow array
tools_raw = tools_str.strip('[]')
granted = set()
for t in tools_raw.split(','):
    t = t.strip().strip('"\'')
    if t and t not in disallowed_set:
        granted.add(t)

# Apply tool-grant rule
has_write = 'Write' in granted
has_edit = 'Edit' in granted
has_task = 'Task' in granted

if not has_write and not has_edit and not has_task:
    # read-only role
    copilot_tools = '[read, search, execute]'
else:
    tool_list = ['read', 'search', 'execute']
    if has_write or has_edit:
        tool_list.append('edit')
    if has_task:
        tool_list.append('agent')
    copilot_tools = '[' + ', '.join(tool_list) + ']'

# Strip prereq from body
body = strip_prereq(body)

# Escape description for YAML double-quoted string
desc_escaped = desc.replace('\\', '\\\\').replace('"', '\\"')

out = f'---\nname: {name}\ndescription: "{desc_escaped}"\ntools: {copilot_tools}\n---\n{body}'

with open(dst_path, 'w') as f:
    f.write(out)
PYEOF

done

# Remove stale agent files
for existing in "$AGENTS_DST"/*.md; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_agents[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale agent: $bname"
  fi
done

echo "Built ${#generated_agents[@]} agent files in .github/agents/"

# ---------------------------------------------------------------------------
# Step 4: Generate .github/prompts/*.prompt.md (one per content/commands/*.md)
#
# VS Code Copilot prompt files use YAML frontmatter:
#   description: (first non-empty non-header body line, <=120 chars)
#
# Body = strip_prereq(content) emitted VERBATIM. No re-injection of any
# prerequisite block. Stale file cleanup applied.
# ---------------------------------------------------------------------------

mkdir -p "$PROMPTS_DST"

declare -a generated_prompts=()

for src in "$CONTENT/commands/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src" .md)"
  dst="$PROMPTS_DST/${base}.prompt.md"
  generated_prompts+=("${base}.prompt.md")

  python3 - "$src" "$dst" "$base" "$REPO_DIR" <<'PYEOF'
import sys, re

src_path, dst_path, cmd_name, repo_dir = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
sys.path.insert(0, repo_dir + '/scripts/lib')
from prereq_strip import strip_prereq

with open(src_path) as f:
    content = f.read()

# Strip any existing YAML frontmatter
fm_match = re.match(r'^---\n.*?\n---\n', content, re.DOTALL)
if fm_match:
    body = content[fm_match.end():]
else:
    body = content

# Apply prereq strip
body = strip_prereq(body)

# Extract description: first non-empty, non-header, non-comment line.
# Skip HTML comment blocks (lines starting with <!-- or inside an open <!-- ... --> block).
description = ''
in_html_comment = False
for line in body.split('\n'):
    stripped = line.strip()
    # Track HTML comment block state
    if in_html_comment:
        if '-->' in stripped:
            in_html_comment = False
        continue
    if stripped.startswith('<!--'):
        if '-->' not in stripped:
            in_html_comment = True
        continue
    if stripped and not stripped.startswith('#') and not stripped.startswith('>'):
        description = stripped[:120]
        break
if not description:
    # Fall back to first header text
    for line in body.split('\n'):
        stripped = line.strip()
        if stripped.startswith('#'):
            description = stripped.lstrip('#').strip()[:120]
            break
if not description:
    description = f'{cmd_name} command'

# Escape description for YAML double-quoted string
desc_escaped = description.replace('\\', '\\\\').replace('"', '\\"')

out = f'---\ndescription: "{desc_escaped}"\n---\n{body}'

with open(dst_path, 'w') as f:
    f.write(out)
PYEOF

done

# Remove stale prompt files
for existing in "$PROMPTS_DST"/*.prompt.md; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_prompts[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale prompt: $bname"
  fi
done

echo "Built ${#generated_prompts[@]} prompt files in .github/prompts/"

# ---------------------------------------------------------------------------
# Step 5: Generate .github/instructions/content-engineering.instructions.md
#
# applyTo: "content/**" scopes this to content authoring sessions.
# Body: concise module-manifest + DRY rules extracted from content/rules/.
# ---------------------------------------------------------------------------

mkdir -p "$INSTRUCTIONS_DST"
CONTENT_INSTR="$INSTRUCTIONS_DST/content-engineering.instructions.md"

cat > "$CONTENT_INSTR" <<'INSTREOF'
---
applyTo: "content/**"
---

# Content Engineering Rules

These rules apply when authoring or modifying files under `content/`.

## Module Manifests

Non-trivial modules should carry a manifest header. Any source file that exports a
public symbol consumed by another module, is over ~50 lines of non-trivial logic, or
implements a side-effecting operation (network, disk, database, external service) should
include a manifest comment at the top of the file. Required fields: Module/Purpose,
Role, Inputs, Outputs, Side-effects, Consumers, Failure modes.

## DRY and Abstraction

Do not Repeat Yourself. Before writing new content:
- Grep the existing files for material that already covers the sub-topic.
- Prefer adding a cross-reference to an existing reference doc over duplicating it.
- Extract repeated rule patterns into a shared reference file and link to it.

If duplication is genuinely appropriate (two paths are about to diverge), state the
reason explicitly in a comment at the top of the section.

## Writing Style

- No em dashes (--). Use regular hyphens (-) instead.
- Concise and direct. Avoid marketing voice.
- Lead with the rule, follow with the rationale.
- Use second-person ("you", "the conductor") not passive voice.

## Cross-Reference Discipline

When a rule in `content/rules/` references detail in `content/references/`, use the
"read on trigger" pattern: state the trigger condition inline, then name the reference
file. Do not inline the full reference body into the rules file.
INSTREOF

echo "Built .github/instructions/content-engineering.instructions.md"

# ---------------------------------------------------------------------------
# Step 6: Install hooks to .github/hooks/
#
# Copies the three hook scripts from .copilot/hooks/ to .github/hooks/.
# Absolute paths are embedded at build time so hooks work regardless of the
# working directory at invocation (which is the user's project, not this repo).
# ---------------------------------------------------------------------------

mkdir -p "$HOOKS_DST"

for hook_src in "$COPILOT_DIR/hooks/"*; do
  [ -f "$hook_src" ] || continue
  hook_name="$(basename "$hook_src")"
  hook_dst="$HOOKS_DST/$hook_name"
  cp "$hook_src" "$hook_dst"
  chmod +x "$hook_dst"
done

echo "Installed hooks to .github/hooks/"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
echo "Copilot adapter build complete."
echo "  .github/copilot-instructions.md"
echo "  .github/agents/          (${#generated_agents[@]} files)"
echo "  .github/prompts/         (${#generated_prompts[@]} files)"
echo "  .github/instructions/    (1 file)"
echo "  .github/hooks/           (hook scripts)"
echo "  .copilot/references/     (hardlinks)"
