#!/usr/bin/env bash
# Purpose: Build the Kimi Code CLI adapter outputs from canonical content/.
# Public API: invoked as `bash .kimi/build.sh`; idempotent.
# Upstream deps: content/commands/, content/references/, content/rules/, content/sections/,
#               content/SKILL.md, content/project-scaffolding.yml, content/templates/,
#               scripts/build-methodology.sh, .kimi/skills/dinostack/SKILL.frontmatter.yaml.
# Downstream consumers: .kimi/AGENTS.md (activation stub only, DS-185 - no embedded
#                       methodology body), .kimi/skills/dinostack/{SKILL.md,METHODOLOGY.md,
#                       references/,sections/,commands/,agents/,templates/,
#                       project-scaffolding.yml}, .kimi/skills/<command>/SKILL.md (one per
#                       content/commands/ file).
# Failure modes: exits non-zero on missing inputs (SKILL.frontmatter.yaml, content/SKILL.md)
#               or assembly script failure. Side-effect: if a prior symlink is present at
#               .kimi/skills/dinostack/SKILL.md (pre-DS-185 layout), it is removed before the
#               new file is written - a plain `>` redirect through that tracked symlink would
#               otherwise write THROUGH it into content/SKILL.md, corrupting the canonical
#               source. Also removes stale .kimi/skills/<name>/ directories whose basename no
#               longer matches any content/commands/*.md source. METHODOLOGY.md itself is
#               always the FULL corpus (unchanged sibling file, the shipped fallback); the
#               SKILL.md embed under "Embedded Resident Content" is the MINIMAL corpus instead
#               (DS-204) with a generated "Deferred at this corpus" pointer block per deferred
#               section, and the SKILL.md footer instructs the reader to open METHODOLOGY.md in
#               the same skill directory when a named trigger fires.
# Performance: standard.

set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
KIMI_DIR="$REPO_DIR/.kimi"
SKILL_DST="$KIMI_DIR/skills/dinostack"

# shellcheck source=scripts/lib/kimi-rules.sh
source "$REPO_DIR/scripts/lib/kimi-rules.sh"

# Portable inode helper (macOS uses -f, Linux uses -c)
get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Build AGENTS.md (DS-185: activation stub only)
#
# .kimi/AGENTS.md is loaded unconditionally by Kimi Code CLI via
# ${KIMI_AGENTS_MD} on every session in this repository - mirroring the
# problem DS-143 solved for Claude Code's always-imported ~/.claude/CLAUDE.md.
# The full methodology body no longer lives here: it is trigger-loaded via
# the `dinostack` skill (built below into .kimi/skills/dinostack/SKILL.md).
# This file stays a minimal, always-resident stub: header, activation
# pointer, and an instruction to load the skill on trigger.
# ---------------------------------------------------------------------------

AGENTS_DST="$KIMI_DIR/AGENTS.md"

cat <<'STUB' > "$AGENTS_DST"
# Agentic Engineering Protocol

This file is a minimal activation stub loaded into every Kimi Code CLI session in this
repository. The full methodology body (delegation, risk classification, quality gates, git
workflow, and the two rules files) is NOT embedded here - it is trigger-loaded via the
`dinostack` skill (DS-185, mirroring the DS-143 change that moved the equivalent always-loaded
body out of Claude Code's `~/.claude/CLAUDE.md`).

**Note:** This file is auto-generated by `.kimi/build.sh`. Do not edit it directly.

## Activation

Activation mode/profile is read from `~/.claude/agentic-engineering.json` - the same shared
config file every adapter uses. Run `bash .kimi/install.sh` to configure it.

## Load the skill on trigger

Before acting on any software development task in this repository (code edits, debugging,
testing, deployment, architecture decisions, git operations, agent orchestration, code review,
refactoring, dependency management, project setup), load the `dinostack` skill:

- `/skill:dinostack` (full methodology), or `/skill:<command-name>` for a specific command
  (e.g. `/skill:ds-wrap`, `/skill:ds-skeptic`, `/skill:ds-implement-ticket`)
- or read `.kimi/skills/dinostack/SKILL.md` directly (local copy) or
  `~/.kimi/skills/dinostack/SKILL.md` (global install) if skill loading is unavailable

The skill embeds the full methodology body - it loads on trigger, not automatically at session
start. When in doubt, invoke it.
STUB

echo "Built AGENTS.md (activation stub)"

# ---------------------------------------------------------------------------
# Build SKILL.md (DS-185: full methodology body, embedded on skill invocation)
#
# Prior to DS-185, .kimi/skills/dinostack/SKILL.md was a static symlink to
# content/SKILL.md (the lean pointer body only - no rules/methodology
# embedded, and no frontmatter, so Kimi could not description-match this
# skill at all). This step embeds the full methodology body directly into a
# real generated SKILL.md file, matching .claude/build.sh's approach for
# DS-143: the always-resident body now lives behind the trigger-loaded
# skill, not in .kimi/AGENTS.md.
# ---------------------------------------------------------------------------

mkdir -p "$SKILL_DST"

# If a prior symlink is present at the destination, remove it first - see
# the module manifest's Failure modes note above for why.
if [[ -L "$SKILL_DST/SKILL.md" ]]; then
  rm -f "$SKILL_DST/SKILL.md"
fi

METHODOLOGY_DST="$SKILL_DST/METHODOLOGY.md"
# Always the FULL corpus - the shipped fallback a reader opens when a
# minimal-corpus "Deferred at this corpus" pointer block fires (see the
# SKILL.md embed below, which uses the minimal corpus instead).
bash "$REPO_DIR/scripts/build-methodology.sh" > "$METHODOLOGY_DST"

# Minimal-corpus stream for the SKILL.md embed below (not written to disk as
# its own file).
METHODOLOGY_MINIMAL="$(bash "$REPO_DIR/scripts/build-methodology.sh" --corpus minimal --full-text-name METHODOLOGY.md)"

FRONTMATTER="$SKILL_DST/SKILL.frontmatter.yaml"
if [[ ! -f "$FRONTMATTER" ]]; then
  echo "build.sh: missing $FRONTMATTER" >&2
  exit 1
fi
if [[ ! -f "$CONTENT/SKILL.md" ]]; then
  echo "build.sh: missing $CONTENT/SKILL.md" >&2
  exit 1
fi
{
  cat "$FRONTMATTER"
  echo
  # Strip leading HTML comment block (manifest header) if present, then emit body.
  perl -0pe 's/\A<!--.*?-->\n\n?//s' "$CONTENT/SKILL.md"
} > "$SKILL_DST/SKILL.md"

# Embed resident content directly into SKILL.md so it loads on skill
# invocation instead of via .kimi/AGENTS.md's (now-removed) always-loaded
# body.
{
  echo ""
  echo "## Embedded Resident Content"
  echo ""
  echo "### METHODOLOGY.md (minimal corpus - see note below)"
  echo ""
  printf '%s\n' "$METHODOLOGY_MINIMAL"
  echo ""
  while IFS= read -r f; do
    name=$(basename "$f")
    echo "### rules/${name}"
    echo ""
    cat "$f"
    echo ""
  done < <(kimi_rules_files "$CONTENT")
  echo ""
  echo "## Note for this Kimi build"
  echo ""
  echo "The rules files named above (rules/code-standards.md, rules/conventions.md) are embedded verbatim under 'Embedded Resident Content' - already in context now that this skill has been invoked. Do not issue a separate Read for them."
  echo ""
  echo "The methodology body embedded above is the MINIMAL corpus: some rules are deferred and replaced by a \"Deferred at this corpus\" pointer block naming a trigger event. If a pointer block's named trigger fires during a task, DO read METHODOLOGY.md in this same skill directory - it carries the full, unfiltered text. That Read is REQUIRED in that case, not redundant."
} >> "$SKILL_DST/SKILL.md"

echo "Built SKILL.md (embedded methodology body)"

# ---------------------------------------------------------------------------
# Ensure symlinks in skill directory
# ---------------------------------------------------------------------------

symlink_dir() {
  local target="$1"
  local link="$2"
  if [[ -L "$link" ]]; then
    local link_dir
    link_dir="$(dirname "$link")"
    local current_abs target_abs
    current_abs="$(python3 -c "import os.path; print(os.path.realpath(os.path.join('$link_dir', os.readlink('$link'))))")"
    target_abs="$(python3 -c "import os.path; print(os.path.realpath(os.path.join('$link_dir', '$target')))")"
    if [[ "$current_abs" == "$target_abs" ]]; then
      echo "  = $(basename "$link") (already linked)"
    else
      rm "$link"
      ln -s "$target" "$link"
      echo "  ~ $(basename "$link") (re-linked)"
    fi
  elif [[ -e "$link" ]]; then
    echo "  ! $(basename "$link") exists and is not a symlink - leaving it"
  else
    ln -s "$target" "$link"
    echo "  + $(basename "$link")"
  fi
}

symlink_dir "../../../content/references" "$SKILL_DST/references"
symlink_dir "../../../content/sections"  "$SKILL_DST/sections"
symlink_dir "../../../content/commands"  "$SKILL_DST/commands"
symlink_dir "../../../content/agents"    "$SKILL_DST/agents"
symlink_dir "../../../content/templates" "$SKILL_DST/templates"

# project-scaffolding.yml: hardlink (not a dir symlink - single file).
# Compare inode (not mere existence) and re-link on mismatch - a stale copy
# left by an older build must not be silently kept, or this replicated
# manifest drifts from content/ with no CI signal (check-adapter-sync only
# diffs generated content, it cannot detect a stale real file that "already
# existed" and was therefore skipped).
SCAFFOLDING_SRC="$REPO_DIR/content/project-scaffolding.yml"
SCAFFOLDING_DST="$SKILL_DST/project-scaffolding.yml"
if [[ -e "$SCAFFOLDING_DST" ]] && [[ "$(get_inode "$SCAFFOLDING_SRC")" == "$(get_inode "$SCAFFOLDING_DST")" ]]; then
  :
else
  rm -f "$SCAFFOLDING_DST"
  ln "$SCAFFOLDING_SRC" "$SCAFFOLDING_DST" 2>/dev/null || cp "$SCAFFOLDING_SRC" "$SCAFFOLDING_DST"
fi
echo "  + project-scaffolding.yml"

# ---------------------------------------------------------------------------
# Create per-command skill directories
# Each command gets its own SKILL.md so it can be invoked directly via
# /skill:<command-name> without requiring /skill:dinostack <command>.
# ---------------------------------------------------------------------------

# Clean up stale per-command skills (commands removed from content/)
for existing_dir in "$KIMI_DIR/skills/"*/; do
  existing_name="$(basename "$existing_dir")"
  if [[ "$existing_name" == "dinostack" ]]; then
    continue
  fi
  if [[ -f "$existing_dir/SKILL.md" ]]; then
    cmd_file="$CONTENT/commands/$existing_name.md"
    if [[ ! -f "$cmd_file" ]]; then
      rm -rf "$existing_dir"
      echo "  - removed stale command skill: $existing_name"
    fi
  fi
done

for cmd_file in "$CONTENT/commands/"*.md; do
  cmd_name="$(basename "$cmd_file" .md)"
  cmd_skill_dir="$KIMI_DIR/skills/$cmd_name"
  mkdir -p "$cmd_skill_dir"

  # Read command content, strip the "# /command" header line
  cmd_content="$(cat "$cmd_file")"
  body="$(echo "$cmd_content" | sed '1{/^# \/.*/d;}')"

  cat > "$cmd_skill_dir/SKILL.md" <<SKILLEOF
---
name: ${cmd_name}
description: >
  dinostack command: ${cmd_name}. Run the ${cmd_name} workflow from the agentic engineering protocol.
---

${body}
SKILLEOF

  echo "  + command skill: $cmd_name"
done

echo "Kimi adapter build complete."
