#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
KIMI_DIR="$REPO_DIR/.kimi"
SKILL_DST="$KIMI_DIR/skills/agentic-engineering"

# ---------------------------------------------------------------------------
# Build AGENTS.md
#
# Flattens all rules files from content/rules/ into a single AGENTS.md,
# which Kimi loads automatically via ${KIMI_AGENTS_MD} when .kimi/AGENTS.md
# exists in the project.
# ---------------------------------------------------------------------------

AGENTS_DST="$KIMI_DIR/AGENTS.md"

{
  cat <<'HEADER'
# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every Kimi Code CLI session in this repository.

**Note:** This file is auto-generated by `.kimi/build.sh` from `content/rules/`. Do not edit it directly - edit the source files in `content/rules/` instead.

For detailed protocol specs (Skeptic loop, subagent protocol, agent team), see the reference docs in `~/.kimi/skills/agentic-engineering/references/` (installed globally) or `.kimi/skills/agentic-engineering/references/` (local copies).

---

HEADER

  cat "$CONTENT/rules/agent-methodology.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/module-manifest.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals
- `findings-flywheel.md` - Per-finding regression test obligation and pattern promotion

These live in `~/.kimi/skills/agentic-engineering/references/` (global install) or `.kimi/skills/agentic-engineering/references/` (local copies).

For command templates (skeptic, implement-ticket, wrap, etc.), see `.kimi/skills/agentic-engineering/commands/`.

## Activation

The activation preflight above references `~/.claude/agentic-engineering.json`. Kimi Code CLI uses the same shared config file for activation mode. Run `bash .kimi/install.sh` to configure it.
FOOTER

} > "$AGENTS_DST"

echo "Built AGENTS.md"

# ---------------------------------------------------------------------------
# Ensure symlinks in skill directory
# ---------------------------------------------------------------------------

mkdir -p "$SKILL_DST"

symlink_dir() {
  local target="$1"
  local link="$2"
  if [[ -L "$link" ]]; then
    current="$(readlink "$link")"
    if [[ "$current" == "$target" ]]; then
      echo "  = $(basename "$link") (already linked)"
    else
      rm "$link"
      ln -s "$target" "$link"
      echo "  ~ $(basename "$link") (re-linked)"
    fi
  elif [[ -e "$link" ]]; then
    echo "  ! $(basename "$link") exists and is not a symlink - leaving it"
  else
    ln -s "$target" "$link"
    echo "  + $(basename "$link")"
  fi
}

symlink_dir "../../../content/references" "$SKILL_DST/references"
symlink_dir "../../../content/rules"     "$SKILL_DST/rules"
symlink_dir "../../../content/commands"  "$SKILL_DST/commands"

echo "Kimi adapter build complete."
