#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
KIMI_DIR="$REPO_DIR/.kimi"
SKILL_DST="$KIMI_DIR/skills/agentic-engineering"

# ---------------------------------------------------------------------------
# Build AGENTS.md
#
# Assembles content/sections/ into a single AGENTS.md via build-methodology.sh,
# which Kimi loads automatically via ${KIMI_AGENTS_MD} when .kimi/AGENTS.md
# exists in the project.
# ---------------------------------------------------------------------------

AGENTS_DST="$KIMI_DIR/AGENTS.md"

{
  cat <<'HEADER'
# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every Kimi Code CLI session in this repository.

**Note:** This file is auto-generated by `.kimi/build.sh` from `content/sections/`. Do not edit it directly - edit the source files in `content/sections/` instead.

For detailed protocol specs (Skeptic loop, subagent protocol, agent team), see the reference docs in `~/.kimi/skills/agentic-engineering/references/` (installed globally) or `.kimi/skills/agentic-engineering/references/` (local copies).

---

HEADER

  bash "$REPO_DIR/scripts/build-methodology.sh"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/module-manifest.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals
- `regression-test-obligation.md` - Per-finding regression test obligation for fixed Critical/Major Skeptic findings

These live in `~/.kimi/skills/agentic-engineering/references/` (global install) or `.kimi/skills/agentic-engineering/references/` (local copies).

For command templates (skeptic, implement-ticket, wrap, etc.), see `.kimi/skills/agentic-engineering/commands/`.

## Activation

The activation preflight above references `~/.claude/agentic-engineering.json`. Kimi Code CLI uses the same shared config file for activation mode. Run `bash .kimi/install.sh` to configure it.
FOOTER

} > "$AGENTS_DST"

echo "Built AGENTS.md"

# ---------------------------------------------------------------------------
# Ensure symlinks in skill directory
# ---------------------------------------------------------------------------

mkdir -p "$SKILL_DST"

symlink_dir() {
  local target="$1"
  local link="$2"
  if [[ -L "$link" ]]; then
    current="$(readlink "$link")"
    if [[ "$current" == "$target" ]]; then
      echo "  = $(basename "$link") (already linked)"
    else
      rm "$link"
      ln -s "$target" "$link"
      echo "  ~ $(basename "$link") (re-linked)"
    fi
  elif [[ -e "$link" ]]; then
    echo "  ! $(basename "$link") exists and is not a symlink - leaving it"
  else
    ln -s "$target" "$link"
    echo "  + $(basename "$link")"
  fi
}

symlink_dir "../../../content/references" "$SKILL_DST/references"
symlink_dir "../../../content/sections"  "$SKILL_DST/sections"
symlink_dir "../../../content/commands"  "$SKILL_DST/commands"
symlink_dir "../../../content/agents"    "$SKILL_DST/agents"

# ---------------------------------------------------------------------------
# Create per-command skill directories
# Each command gets its own SKILL.md so it can be invoked directly via
# /skill:<command-name> without requiring /skill:agentic-engineering <command>.
# ---------------------------------------------------------------------------

# Clean up stale per-command skills (commands removed from content/)
for existing_dir in "$KIMI_DIR/skills/"*/; do
  existing_name="$(basename "$existing_dir")"
  if [[ "$existing_name" == "agentic-engineering" ]]; then
    continue
  fi
  if [[ -f "$existing_dir/SKILL.md" ]]; then
    cmd_file="$CONTENT/commands/$existing_name.md"
    if [[ ! -f "$cmd_file" ]]; then
      rm -rf "$existing_dir"
      echo "  - removed stale command skill: $existing_name"
    fi
  fi
done

for cmd_file in "$CONTENT/commands/"*.md; do
  cmd_name="$(basename "$cmd_file" .md)"
  cmd_skill_dir="$KIMI_DIR/skills/$cmd_name"
  mkdir -p "$cmd_skill_dir"

  # Read command content, strip the "# /command" header line
  cmd_content="$(cat "$cmd_file")"
  body="$(echo "$cmd_content" | sed '1{/^# \/.*/d;}')"

  cat > "$cmd_skill_dir/SKILL.md" <<SKILLEOF
---
name: ${cmd_name}
description: >
  agentic-engineering command: ${cmd_name}. Run the ${cmd_name} workflow from the agentic engineering protocol.
---

${body}
SKILLEOF

  echo "  + command skill: $cmd_name"
done

echo "Kimi adapter build complete."
