#!/usr/bin/env bash
# Purpose: Deterministically generate the tier-specific implement-ticket command
#          bodies from the annotated single-source file
#          `content/commands/implement-ticket-body.md` using the tier-filter.
#          Produces:
#            content/commands/implement-ticket-full.md
#            content/commands/implement-ticket-medium.md
#          (implement-ticket-minimal.md and the router implement-ticket.md are
#          hand-authored and not regenerated by this script.)
#
# Public API:
#   bash scripts/build-commands.sh                 # build all generated files
#   bash scripts/build-commands.sh full             # build only the full body
#   bash scripts/build-commands.sh medium           # build only the medium body
#
# Generated-file marker: the first line of every generated file is the comment
#   `<!-- Generated from implement-ticket-body.md - do not edit. -->`
#   downstream build steps (e.g. adapter `build.sh`) copy these files into
#   the adapter's commands directory; the marker is preserved by the copy.
#
# Upstream deps: content/commands/implement-ticket-body.md (single source);
#               scripts/lib/tier-filter.py.
#
# Downstream consumers: .claude/build.sh, .codex/build.sh, .cursor/build.sh,
#                       .gemini/build.sh, future adapter builds. Each adapter's
#                       build.sh MUST call `scripts/build-commands.sh` before
#                       copying the command files into the harness's commands dir.
#                       The adapter-sync CI workflow runs the build and diffs
#                       the output against the committed copy; a missing
#                       regeneration fails the workflow.
#
# Failure modes: exits non-zero if the body source is missing, the tier-filter
#                rejects the body (unbalanced begin/end, unknown tier name), or
#                the destination directory is not writable. Idempotent.
#
# Performance: O(size of body source); two filter passes (one per tier).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BODY_SRC="$REPO_DIR/content/commands/implement-ticket-body.md"
COMMANDS_DST="$REPO_DIR/content/commands"
TIER_FILTER="$REPO_DIR/scripts/lib/tier-filter.py"
GENERATED_HEADER='<!-- Generated from implement-ticket-body.md - do not edit. -->'

if [ ! -f "$BODY_SRC" ]; then
	echo "build-commands.sh: body source missing: $BODY_SRC" >&2
	exit 1
fi
if [ ! -f "$TIER_FILTER" ]; then
	echo "build-commands.sh: tier-filter missing: $TIER_FILTER" >&2
	exit 1
fi
if [ ! -d "$COMMANDS_DST" ]; then
	echo "build-commands.sh: commands dir missing: $COMMANDS_DST" >&2
	exit 1
fi

# Tier filter CLI: python3 scripts/lib/tier-filter.py <tier> < input.md > output.md
# Header line: prepended verbatim to the filtered output for every generated file.

emit_tier() {
	local tier="$1"
	local dst="$COMMANDS_DST/implement-ticket-${tier}.md"
	local tmp
	tmp="$(mktemp -t build-commands.XXXXXX)" || {
		echo "build-commands.sh: mktemp failed" >&2
		exit 1
	}
	# shellcheck disable=SC2094  # tmp is intentionally a concrete file path
	{
		printf '%s\n' "$GENERATED_HEADER"
		python3 "$TIER_FILTER" "$tier" <"$BODY_SRC"
	} >"$tmp"
	mv -f "$tmp" "$dst"
	echo "build-commands.sh: wrote $dst ($(wc -c <"$dst") bytes)"
}

WHAT="${1:-all}"
case "$WHAT" in
full)
	emit_tier full
	;;
medium)
	emit_tier medium
	;;
all)
	emit_tier full
	emit_tier medium
	;;
*)
	echo "build-commands.sh: invalid target '$WHAT' (expected full|medium|all)" >&2
	exit 2
	;;
esac

echo "build-commands.sh: done"
