#!/usr/bin/env bash
# Module: .gemini/build.sh
# Role: Build script for the Gemini CLI adapter
# Inputs: content/rules/*.md, content/references/*.md, content/commands/*.md, content/agents/*.md
# Outputs: .gemini/skills/dinostack/SKILL.md (full assembled methodology body,
#          trigger-loaded via Gemini CLI's `activate_skill` - DS-184),
#          .gemini/GEMINI.md (a small always-loaded stub pointing at the skill
#          - no longer carries the methodology body itself, DS-184),
#          .gemini/references/*.md (hardlinks), .gemini/commands/*.toml
#          (generated TOML), .gemini/agents/*.md (generated markdown)
# Side-effects: removes stale generated files from previous builds
# Consumers: .gemini/install.sh, hooks/pre-commit, .github/workflows/adapter-sync.yml,
#            scripts/build-all.sh, content/commands/ds-update-agentic-engineering.md,
#            scripts/check-gemini-skill-budget.sh (measures the SKILL.md and
#            GEMINI.md this script produces)
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
GEMINI_DIR="$REPO_DIR/.gemini"
REFS_DST="$GEMINI_DIR/references"
COMMANDS_DST="$GEMINI_DIR/commands"
AGENTS_DST="$GEMINI_DIR/agents"
SKILL_DST="$GEMINI_DIR/skills/dinostack"

# ---------------------------------------------------------------------------
# Portable inode helper (macOS uses -f, Linux uses -c)
# ---------------------------------------------------------------------------

get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Step 1: Generate the dinostack skill (SKILL.md) and the GEMINI.md stub
#
# DS-184: Gemini CLI supports project-local trigger-loaded skills
# (.gemini/skills/<name>/SKILL.md, discovered at session start via
# `activate_skill` - see docs/cli/skills.md on google-gemini/gemini-cli).
# The full assembled methodology body (all content/sections/*.md plus
# content/rules/code-standards.md and content/rules/conventions.md, same
# content this file used to write directly into GEMINI.md) now lives in
# .gemini/skills/dinostack/SKILL.md instead, so it loads on trigger rather
# than unconditionally in every session. GEMINI.md is regenerated as a
# small always-loaded stub that points at the skill.
# ---------------------------------------------------------------------------

GEMINI_MD_DST="$GEMINI_DIR/GEMINI.md"
SKILL_MD_DST="$SKILL_DST/SKILL.md"

mkdir -p "$SKILL_DST"

{
  cat <<'SKILL_FRONTMATTER'
---
name: "dinostack"
description: >
  Apply when the user mentions any software development work: implementing features, fixing bugs,
  reviewing or refactoring code, debugging, testing, deploying, working with agents or subagents,
  making architecture decisions, setting up projects, managing dependencies, writing scripts, or
  any task that involves reading, writing, or reasoning about code and systems.
---

# Agentic Engineering Protocol

This skill loads the full agentic engineering methodology on trigger, instead of unconditionally in every Gemini CLI session.

**Note:** This file is auto-generated by `.gemini/build.sh` from `content/sections/` and `content/rules/`. Do not edit it directly - edit the source files instead.

For detailed protocol specs, see reference docs in `.gemini/references/` or `~/.gemini/references/` (if installed globally).

---

SKILL_FRONTMATTER

  bash "$REPO_DIR/scripts/build-methodology.sh"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals

These live in `.gemini/references/` (local copies in this repo) or `~/.gemini/references/` after install.

For command templates (skeptic, implement-ticket, wrap, etc.), see `.gemini/commands/`.
FOOTER

} > "$SKILL_MD_DST"

echo "Built .gemini/skills/dinostack/SKILL.md"

{
  cat <<'STUB'
# Agentic Engineering Protocol (dinostack)

This project uses the DinoStack agentic engineering methodology. The full protocol body is
trigger-loaded via the `dinostack` skill - it does not load unconditionally from this file.

**Note:** This file is auto-generated by `.gemini/build.sh`. Do not edit it directly.

## Loading the methodology

Invoke the `dinostack` skill (`activate_skill`) before any software development work:
implementing features, fixing bugs, reviewing or refactoring code, debugging, testing,
deploying, working with agents or subagents, making architecture decisions, setting up
projects, managing dependencies, writing scripts, or any task that involves reading,
writing, or reasoning about code and systems. The skill lives at
`.gemini/skills/dinostack/SKILL.md` (project-local) or `~/.gemini/skills/dinostack/SKILL.md`
(installed globally).

**Activation preflight:** before doing implementation work in a project, check whether
agentic engineering is active there. See the "Activation preflight" section (§01) inside
the `dinostack` skill body once loaded.

**Known limitation - headless/non-interactive runs:** Gemini CLI denies `activate_skill` by
default outside an interactive session (see `.gemini/README.md` §Trigger-loaded methodology
(DS-184), "Known limitation" paragraph, for the full explanation and both override routes).
A scripted, non-interactive Gemini run will get neither this stub's full body nor the skill
unless the operator has explicitly opted in to one of those overrides.

---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals

These live in `.gemini/references/` (local copies in this repo) or `~/.gemini/references/` after install.

For command templates (skeptic, implement-ticket, wrap, etc.), see `.gemini/commands/`.
STUB
} > "$GEMINI_MD_DST"

echo "Built GEMINI.md stub"

# ---------------------------------------------------------------------------
# Step 2: Hardlink references/
#
# .gemini/references/ contains hardlinks to content/references/ for users
# browsing the repo without installing.
# ---------------------------------------------------------------------------

mkdir -p "$REFS_DST"

hardlink_from_content() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]] && [[ "$(get_inode "$src")" == "$(get_inode "$dst")" ]]; then
    return
  fi
  rm -f "$dst"
  ln "$src" "$dst"
}

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$REFS_DST/$(basename "$src")"
done

echo "Rebuilt references/ hardlinks"

# ---------------------------------------------------------------------------
# Step 3: Generate commands/ (TOML slash-command files)
#
# For each content/commands/*.md, generate a Gemini TOML slash-command file.
# Format:
#   description = "<first non-empty non-header line from body>"
#   prompt = """<full markdown body>"""
#
# The /dinostack prerequisite blockquote is NOT added here -
# it is Claude Code-specific and never appears in content/commands/*.md.
#
# If the command body contains any """ sequences, they are escaped as \"\"\"
# to avoid prematurely terminating the TOML triple-quoted string.
# ---------------------------------------------------------------------------

mkdir -p "$COMMANDS_DST"

# Track generated files for stale cleanup
declare -a generated_tomls=()

for src in "$CONTENT/commands/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src" .md)"
  echo "  building ${base}.toml"
  dst="$COMMANDS_DST/${base}.toml"
  generated_tomls+=("${base}.toml")

  # Read body (skip frontmatter if present, otherwise use full file)
  # Gemini commands are plain markdown with no frontmatter, but handle it
  # defensively in case content evolves.
  body_lines=()
  in_fm=0
  past_fm=0
  first_line=1

  while IFS= read -r line; do
    if [[ $first_line -eq 1 ]]; then
      first_line=0
      if [[ "$line" == "---" ]]; then
        in_fm=1
        continue
      fi
      # No frontmatter - treat entire file as body
      past_fm=1
      body_lines+=("$line")
      continue
    fi
    if [[ $in_fm -eq 1 ]]; then
      if [[ "$line" == "---" ]]; then
        in_fm=0
        past_fm=1
      fi
      continue
    fi
    body_lines+=("$line")
  done < "$src"

  # Extract description: first non-empty line of the body that is not a
  # markdown header (does not start with #) and not inside a leading HTML
  # comment block (<!-- ... -->) - several command sources open with a
  # "Purpose:" comment block before the heading, and without this skip the
  # description degrades to the literal "<!--" opening marker.
  description=""
  in_html_comment=0
  for bline in "${body_lines[@]}"; do
    trimmed="${bline#"${bline%%[![:space:]]*}"}"  # ltrim
    if [[ $in_html_comment -eq 1 ]]; then
      if [[ "$trimmed" == *"-->"* ]]; then
        in_html_comment=0
      fi
      continue
    fi
    if [[ "$trimmed" == "<!--"* ]]; then
      if [[ "$trimmed" != *"-->"* ]]; then
        in_html_comment=1
      fi
      continue
    fi
    if [[ -n "$trimmed" ]] && [[ "$trimmed" != \#* ]]; then
      description="$trimmed"
      break
    fi
  done
  if [[ -z "$description" ]]; then
    # All non-empty lines are headers - try first header text without leading #
    for bline in "${body_lines[@]}"; do
      trimmed="${bline#"${bline%%[![:space:]]*}"}"
      if [[ -n "$trimmed" ]]; then
        # Strip leading # chars and trim
        stripped="${trimmed###}"
        stripped="${stripped# }"
        description="$stripped"
        break
      fi
    done
  fi
  if [[ -z "$description" ]]; then
    description="${base} command"
  fi

  # Truncate description to 120 chars to keep TOML readable
  if [[ ${#description} -gt 120 ]]; then
    description="${description:0:117}..."
  fi

  # Build body string from accumulated lines
  if [[ ${#body_lines[@]} -gt 0 ]]; then
    OLD_IFS="$IFS"
    IFS=$'\n'
    body_content="${body_lines[*]}"
    IFS="$OLD_IFS"
  else
    body_content=""
  fi

  # Escape backslashes, then sequences of 3+ double-quotes, for the TOML
  # multi-line basic string. Bash's own `${var//pattern/repl}` parameter
  # substitution is prohibitively slow on large bodies (DS-135 follow-up) -
  # a single backslash-escape pass alone did not complete in 200s on a
  # ~335KB body under bash 3.2.57 (the default macOS /bin/bash). Route both
  # passes through python3 (already a repo dependency) instead. A trailing
  # sentinel byte guards the two escape passes' output against command
  # substitution's trailing-newline stripping, since a body that ends in a
  # blank line would otherwise silently lose that trailing newline.
  body_escaped="$(
    printf '%s' "$body_content" | python3 -c '
import sys
s = sys.stdin.read()
s = s.replace("\\", "\\\\")
s = s.replace("\"\"\"", "\\\"\\\"\\\"")
sys.stdout.write(s)
'
    printf '\x01'
  )"
  body_escaped="${body_escaped%$'\x01'}"

  # Escape description for TOML basic string (backslash then double-quote)
  desc_escaped="${description//\\/\\\\}"
  desc_escaped="${desc_escaped//\"/\\\"}"

  {
    echo "# Generated by .gemini/build.sh from content/commands/$(basename "$src")"
    echo "# Do not edit directly - edit the source markdown file instead."
    echo ""
    echo "description = \"${desc_escaped}\""
    echo ""
    echo "prompt = \"\"\""
    printf '%s' "$body_escaped"
    echo ""
    echo "\"\"\""
  } > "$dst"

done

# Remove stale TOML files
for existing in "$COMMANDS_DST"/*.toml; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_tomls[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale command TOML: $bname"
  fi
done

echo "Built ${#generated_tomls[@]} command TOML files in .gemini/commands/"

# ---------------------------------------------------------------------------
# Step 4: Generate agents/ (markdown+frontmatter files from content/agents/*.md)
#
# For each content/agents/<name>.md, generate .gemini/agents/<name>.md with:
#   - kind: local  added if not already present
#   - model:       field removed (agents inherit the session model)
#   - All other frontmatter fields preserved verbatim
#   - Body preserved verbatim
#
# Transform is pure line-by-line string operations (no YAML library needed).
# ---------------------------------------------------------------------------

mkdir -p "$AGENTS_DST"

# Track generated files for stale cleanup
declare -a generated_agents=()

for src in "$CONTENT/agents/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src")"
  dst="$AGENTS_DST/$base"
  generated_agents+=("$base")

  # Parse file in 3 phases: before frontmatter, inside frontmatter, body
  # Phase 0: looking for opening ---
  # Phase 1: inside frontmatter (between first and second ---)
  # Phase 2: body (after closing ---)

  phase=0
  has_kind=0
  fm_lines=()
  body_lines=()

  while IFS= read -r line; do
    if [[ $phase -eq 0 ]]; then
      if [[ "$line" == "---" ]]; then
        phase=1
      fi
      # (pre-frontmatter lines are ignored - content/agents/*.md always starts with ---)
      continue
    fi
    if [[ $phase -eq 1 ]]; then
      if [[ "$line" == "---" ]]; then
        phase=2
        continue
      fi
      # Skip model: lines
      if [[ "$line" == model:* ]] || [[ "$line" == "model: "* ]]; then
        continue
      fi
      # Skip disallowedTools: lines (redundant in gemini-cli 0.47+; tools is an allowlist)
      if [[ "$line" == disallowedTools:* ]] || [[ "$line" == "disallowedTools: "* ]]; then
        continue
      fi
      # Transform tools: comma-string -> YAML flow array with gemini tool names
      # gemini-cli 0.47 requires an array and only accepts its own tool name identifiers.
      # Map Claude Code tool names to gemini equivalents:
      #   Read  -> read_file        Glob -> glob        Grep -> grep_search
      #   Bash  -> run_shell_command  Write -> write_file  Edit -> replace
      #   Task  -> invoke_agent
      if [[ "$line" == tools:* ]]; then
        val="${line#tools:}"
        val="${val# }"  # strip leading space
        if [[ "$val" != "["* ]]; then
          # Split on commas, trim whitespace, map names, build [item1, item2, ...] flow array
          IFS=',' read -ra items <<< "$val"
          arr="["
          for item in "${items[@]}"; do
            trimmed="${item#"${item%%[![:space:]]*}"}"  # ltrim
            trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"  # rtrim
            # Map Claude Code tool names -> gemini tool names
            case "$trimmed" in
              Read)  trimmed="read_file" ;;
              Glob)  trimmed="glob" ;;
              Grep)  trimmed="grep_search" ;;
              Bash)  trimmed="run_shell_command" ;;
              Write) trimmed="write_file" ;;
              Edit)  trimmed="replace" ;;
              Task)  trimmed="invoke_agent" ;;
            esac
            arr+="$trimmed, "
          done
          arr="${arr%, }]"  # remove trailing ", " and close
          line="tools: $arr"
        fi
      fi
      # Quote description: values to prevent YAML misparse of colon-space sequences
      if [[ "$line" == description:* ]]; then
        val="${line#description:}"
        val="${val# }"  # strip leading space
        # Only quote if not already double-quoted
        if [[ "$val" != '"'* ]]; then
          # Escape backslashes then double-quotes in value
          val="${val//\\/\\\\}"
          val="${val//\"/\\\"}"
          line="description: \"$val\""
        fi
      fi
      # Track if kind: is already present
      if [[ "$line" == kind:* ]] || [[ "$line" == "kind: "* ]]; then
        has_kind=1
      fi
      fm_lines+=("$line")
      continue
    fi
    # Phase 2: body
    body_lines+=("$line")
  done < "$src"

  # Write output file
  {
    echo "---"
    for fm_line in "${fm_lines[@]}"; do
      echo "$fm_line"
    done
    if [[ $has_kind -eq 0 ]]; then
      echo "kind: local"
    fi
    echo "---"
    for body_line in "${body_lines[@]}"; do
      echo "$body_line"
    done
  } > "$dst"

done

# Remove stale agent files
for existing in "$AGENTS_DST"/*.md; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_agents[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale agent file: $bname"
  fi
done

echo "Built ${#generated_agents[@]} agent files in .gemini/agents/"

# project-scaffolding.yml and templates/: hardlink so ds-migrate can resolve from adapter
hardlink_from_content "$CONTENT/project-scaffolding.yml" "$GEMINI_DIR/project-scaffolding.yml"
mkdir -p "$GEMINI_DIR/templates/.agentic"
for tmpl_src in "$CONTENT"/templates/.agentic/*; do
  [[ -f "$tmpl_src" ]] || continue
  hardlink_from_content "$tmpl_src" "$GEMINI_DIR/templates/.agentic/$(basename "$tmpl_src")"
done
echo "Rebuilt project-scaffolding.yml and templates/"

echo "Gemini adapter build complete."
