#!/usr/bin/env bash
# Module: .gemini/build.sh
# Role: Build script for the Gemini CLI adapter
# Inputs: content/rules/*.md, content/references/*.md, content/commands/*.md, content/agents/*.md
# Outputs: .gemini/GEMINI.md, .gemini/references/*.md (hardlinks),
#          .gemini/commands/*.toml (generated TOML), .gemini/agents/*.md (generated markdown)
# Side-effects: removes stale generated files from previous builds
# Consumers: .gemini/install.sh, hooks/pre-commit
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="$REPO_DIR/content"
GEMINI_DIR="$REPO_DIR/.gemini"
REFS_DST="$GEMINI_DIR/references"
COMMANDS_DST="$GEMINI_DIR/commands"
AGENTS_DST="$GEMINI_DIR/agents"

# ---------------------------------------------------------------------------
# Portable inode helper (macOS uses -f, Linux uses -c)
# ---------------------------------------------------------------------------

get_inode() {
  if stat -c %i /dev/null >/dev/null 2>&1; then
    stat -c %i "$1"
  else
    stat -f %i "$1"
  fi
}

# ---------------------------------------------------------------------------
# Step 1: Generate GEMINI.md
#
# Concatenates all 3 rules files from content/rules/ into a single GEMINI.md,
# which Gemini CLI loads automatically from ~/.gemini/GEMINI.md (global) or
# .gemini/GEMINI.md (project-scoped). A header and protocol reference footer
# are prepended/appended.
# ---------------------------------------------------------------------------

GEMINI_MD_DST="$GEMINI_DIR/GEMINI.md"

{
  cat <<'HEADER'
# Agentic Engineering Protocol

This file loads the agentic engineering methodology into every Gemini CLI session in this repository.

**Note:** This file is auto-generated by `.gemini/build.sh` from `content/rules/`. Do not edit it directly - edit the source files in `content/rules/` instead.

For detailed protocol specs, see reference docs in `.gemini/references/` or `~/.gemini/references/` (if installed globally).

---

HEADER

  bash "$REPO_DIR/scripts/build-methodology.sh"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/code-standards.md"
  echo ""
  echo "---"
  echo ""
  cat "$CONTENT/rules/conventions.md"

  cat <<'FOOTER'


---

## Protocol Reference

For detailed protocol specs, see the reference docs:

- `skeptic-protocol.md` - Skeptic loop orchestration, findings classification, sign-off format
- `subagent-protocol.md` - Parallel spawning rules, worktree isolation, task decomposition
- `agent-team.md` - Named agent roles, composed flows, decision rules
- `design-goals.md` - System design principles and goals

These live in `.gemini/references/` (local copies in this repo) or `~/.gemini/references/` after install.

For command templates (skeptic, implement-ticket, wrap, etc.), see `.gemini/commands/`.
FOOTER

} > "$GEMINI_MD_DST"

echo "Built GEMINI.md"

# ---------------------------------------------------------------------------
# Step 2: Hardlink references/
#
# .gemini/references/ contains hardlinks to content/references/ for users
# browsing the repo without installing.
# ---------------------------------------------------------------------------

mkdir -p "$REFS_DST"

hardlink_from_content() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]] && [[ "$(get_inode "$src")" == "$(get_inode "$dst")" ]]; then
    return
  fi
  rm -f "$dst"
  ln "$src" "$dst"
}

for src in "$CONTENT/references/"*.md; do
  hardlink_from_content "$src" "$REFS_DST/$(basename "$src")"
done

echo "Rebuilt references/ hardlinks"

# ---------------------------------------------------------------------------
# Step 3: Generate commands/ (TOML slash-command files)
#
# For each content/commands/*.md, generate a Gemini TOML slash-command file.
# Format:
#   description = "<first non-empty non-header line from body>"
#   prompt = """<full markdown body>"""
#
# The /agentic-engineering prerequisite blockquote is NOT added here -
# it is Claude Code-specific and never appears in content/commands/*.md.
#
# If the command body contains any """ sequences, they are escaped as \"\"\"
# to avoid prematurely terminating the TOML triple-quoted string.
# ---------------------------------------------------------------------------

mkdir -p "$COMMANDS_DST"

# Track generated files for stale cleanup
declare -a generated_tomls=()

for src in "$CONTENT/commands/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src" .md)"
  dst="$COMMANDS_DST/${base}.toml"
  generated_tomls+=("${base}.toml")

  # Read body (skip frontmatter if present, otherwise use full file)
  # Gemini commands are plain markdown with no frontmatter, but handle it
  # defensively in case content evolves.
  body_lines=()
  in_fm=0
  past_fm=0
  first_line=1

  while IFS= read -r line; do
    if [[ $first_line -eq 1 ]]; then
      first_line=0
      if [[ "$line" == "---" ]]; then
        in_fm=1
        continue
      fi
      # No frontmatter - treat entire file as body
      past_fm=1
      body_lines+=("$line")
      continue
    fi
    if [[ $in_fm -eq 1 ]]; then
      if [[ "$line" == "---" ]]; then
        in_fm=0
        past_fm=1
      fi
      continue
    fi
    body_lines+=("$line")
  done < "$src"

  # Extract description: first non-empty line of the body that is not a
  # markdown header (does not start with #). Strip leading # chars if the
  # only non-empty lines are headers (fall back to "<name> command").
  description=""
  for bline in "${body_lines[@]}"; do
    trimmed="${bline#"${bline%%[![:space:]]*}"}"  # ltrim
    if [[ -n "$trimmed" ]] && [[ "$trimmed" != \#* ]]; then
      description="$trimmed"
      break
    fi
  done
  if [[ -z "$description" ]]; then
    # All non-empty lines are headers - try first header text without leading #
    for bline in "${body_lines[@]}"; do
      trimmed="${bline#"${bline%%[![:space:]]*}"}"
      if [[ -n "$trimmed" ]]; then
        # Strip leading # chars and trim
        stripped="${trimmed###}"
        stripped="${stripped# }"
        description="$stripped"
        break
      fi
    done
  fi
  if [[ -z "$description" ]]; then
    description="${base} command"
  fi

  # Truncate description to 120 chars to keep TOML readable
  if [[ ${#description} -gt 120 ]]; then
    description="${description:0:117}..."
  fi

  # Build body string from accumulated lines
  body_content=""
  first_body=1
  for bline in "${body_lines[@]}"; do
    if [[ $first_body -eq 1 ]]; then
      body_content="$bline"
      first_body=0
    else
      body_content="$body_content
$bline"
    fi
  done

  # Escape backslashes for TOML multi-line basic string
  body_escaped="${body_content//\\/\\\\}"
  # Escape sequences of 3+ double-quotes so they don't terminate the TOML string
  body_escaped="${body_escaped//\"\"\"/\\\"\\\"\\\"}"

  # Escape description for TOML basic string (backslash then double-quote)
  desc_escaped="${description//\\/\\\\}"
  desc_escaped="${desc_escaped//\"/\\\"}"

  {
    echo "# Generated by .gemini/build.sh from content/commands/$(basename "$src")"
    echo "# Do not edit directly - edit the source markdown file instead."
    echo ""
    echo "description = \"${desc_escaped}\""
    echo ""
    echo "prompt = \"\"\""
    printf '%s' "$body_escaped"
    echo ""
    echo "\"\"\""
  } > "$dst"

done

# Remove stale TOML files
for existing in "$COMMANDS_DST"/*.toml; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_tomls[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale command TOML: $bname"
  fi
done

echo "Built ${#generated_tomls[@]} command TOML files in .gemini/commands/"

# ---------------------------------------------------------------------------
# Step 4: Generate agents/ (markdown+frontmatter files from content/agents/*.md)
#
# For each content/agents/<name>.md, generate .gemini/agents/<name>.md with:
#   - kind: local  added if not already present
#   - model:       field removed (agents inherit the session model)
#   - All other frontmatter fields preserved verbatim
#   - Body preserved verbatim
#
# Transform is pure line-by-line string operations (no YAML library needed).
# ---------------------------------------------------------------------------

mkdir -p "$AGENTS_DST"

# Track generated files for stale cleanup
declare -a generated_agents=()

for src in "$CONTENT/agents/"*.md; do
  [ -f "$src" ] || continue

  base="$(basename "$src")"
  dst="$AGENTS_DST/$base"
  generated_agents+=("$base")

  # Parse file in 3 phases: before frontmatter, inside frontmatter, body
  # Phase 0: looking for opening ---
  # Phase 1: inside frontmatter (between first and second ---)
  # Phase 2: body (after closing ---)

  phase=0
  has_kind=0
  fm_lines=()
  body_lines=()

  while IFS= read -r line; do
    if [[ $phase -eq 0 ]]; then
      if [[ "$line" == "---" ]]; then
        phase=1
      fi
      # (pre-frontmatter lines are ignored - content/agents/*.md always starts with ---)
      continue
    fi
    if [[ $phase -eq 1 ]]; then
      if [[ "$line" == "---" ]]; then
        phase=2
        continue
      fi
      # Skip model: lines
      if [[ "$line" == model:* ]] || [[ "$line" == "model: "* ]]; then
        continue
      fi
      # Track if kind: is already present
      if [[ "$line" == kind:* ]] || [[ "$line" == "kind: "* ]]; then
        has_kind=1
      fi
      fm_lines+=("$line")
      continue
    fi
    # Phase 2: body
    body_lines+=("$line")
  done < "$src"

  # Write output file
  {
    echo "---"
    for fm_line in "${fm_lines[@]}"; do
      echo "$fm_line"
    done
    if [[ $has_kind -eq 0 ]]; then
      echo "kind: local"
    fi
    echo "---"
    for body_line in "${body_lines[@]}"; do
      echo "$body_line"
    done
  } > "$dst"

done

# Remove stale agent files
for existing in "$AGENTS_DST"/*.md; do
  [ -f "$existing" ] || continue
  bname="$(basename "$existing")"
  found=0
  for gen in "${generated_agents[@]}"; do
    if [[ "$gen" == "$bname" ]]; then
      found=1
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    rm "$existing"
    echo "Removed stale agent file: $bname"
  fi
done

echo "Built ${#generated_agents[@]} agent files in .gemini/agents/"

# project-scaffolding.yml and templates/: hardlink so agentic-migrate can resolve from adapter
hardlink_from_content "$CONTENT/project-scaffolding.yml" "$GEMINI_DIR/project-scaffolding.yml"
mkdir -p "$GEMINI_DIR/templates/.agentic"
hardlink_from_content "$CONTENT/templates/.agentic/config.json" "$GEMINI_DIR/templates/.agentic/config.json"
echo "Rebuilt project-scaffolding.yml and templates/"

echo "Gemini adapter build complete."
