name: dco

on:
  pull_request:
    branches:
      - main

jobs:
  dco-check:
    name: DCO Signed-off-by check
    runs-on: ubuntu-latest
    steps:
      - name: Get PR commits
        id: pr-commits
        uses: tim-actions/get-pr-commits@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Signed-off-by on every commit
        uses: tim-actions/dco@v1.1.0
        with:
          commits: ${{ steps.pr-commits.outputs.commits }}
